vim.g.mapleader = " "
vim.g.maplocalleader = " "
-- indent-blankline
require("ajay.gitsigns")
require("ajay.lazygit")
require("ajay.options")
require("ajay.keymaps")
require("ajay.plugins")
require("ajay.colorscheme")
require("ajay.cmp")
require("ajay.neotree")
require("ajay.lsp")
require("ajay.null-ls")
require("ajay.autoformat")
require("ajay.dashboard")
require("ajay.comment")
require("ajay.telescope")
require("ajay.treesitter")
require("ajay.dap")
require("ajay.conform")
require("ajay.copilot")
require("ajay.jupyter")
-- require("ajay.transparency")
